import { NextResponse } from 'next/server';

export async function GET() {
  return NextResponse.json({
    STELLAR_HORIZON_URL: process.env.NEXT_PUBLIC_STELLAR_HORIZON_URL || 'https://horizon-testnet.stellar.org',
    SOROBAN_RPC_URL: process.env.NEXT_PUBLIC_SOROBAN_RPC_URL || 'https://soroban-testnet.stellar.org',
    // Strip surrounding quotes just in case they were left in the env file
    STELLAR_NETWORK_PASSPHRASE: (process.env.NEXT_PUBLIC_STELLAR_NETWORK_PASSPHRASE || 'Test SDF Network ; September 2015').replace(/^["']|["']$/g, ''),
    
    POOL_CONTRACT_ID: process.env.NEXT_PUBLIC_SWARP_CONTRACT_ID || process.env.NEXT_PUBLIC_POOL_CONTRACT_ID || 'CBC4DNL77PU5BNTXC6APQE46FU5JDY72OOTKGHRVUTCCAT6RNLLLYDYS',
    LEGACY_POOL_CONTRACT_ID: process.env.NEXT_PUBLIC_LEGACY_POOL_CONTRACT_ID,
    VERIFIER_CONTRACT_ID: process.env.NEXT_PUBLIC_VERIFIER_CONTRACT_ID || 'CAMZZMFIPURXP2ZDION6K3RN62ORU3MHE6GWT6JB2OXPB4WOYNTJA2VZ',
    
    USDC_SAC_ID: process.env.NEXT_PUBLIC_USDC_SAC_ID || 'CDTGDHE3GHSNIYMRHBN7PMSGXXR73KHZ4KS2ZEBAIDOS6THPOLMHL5LG',
    EURC_SAC_ID: process.env.NEXT_PUBLIC_EURC_SAC_ID || 'CD6KJAOC4OQ2LQC4WQZHUFW2SMINOPC6SXUOCKN5UAX2KHVBSXUXQIDG',
    MGUSD_SAC_ID: process.env.NEXT_PUBLIC_MGUSD_SAC_ID || '',
    YLDS_SAC_ID: process.env.NEXT_PUBLIC_YLDS_SAC_ID || '',
    XLM_SAC_ID: process.env.NEXT_PUBLIC_XLM_SAC_ID || 'CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC',
    
    USDC_ISSUER_ADDRESS: process.env.NEXT_PUBLIC_USDC_ISSUER_ADDRESS || 'GCUSVTVSWAHQMDO2KQC5H2TC6RCB7UNRQ5YD3XCPTNSCYWIQYMPN6VVX',
    EURC_ISSUER_ADDRESS: process.env.NEXT_PUBLIC_EURC_ISSUER_ADDRESS || '',
    MGUSD_ISSUER_ADDRESS: process.env.NEXT_PUBLIC_MGUSD_ISSUER_ADDRESS || '',
    YLDS_ISSUER_ADDRESS: process.env.NEXT_PUBLIC_YLDS_ISSUER_ADDRESS || '',
  });
}
