#![no_std]

extern crate alloc;

use soroban_sdk::{contract, contracterror, contractimpl, Bytes, BytesN, Env, Vec};
use ultrahonk_soroban_verifier::{UltraHonkVerifier, PROOF_BYTES};

// ── Verification Key ─────────────────────────────────────────────────────────
// Generated by: bb write_vk -b circuits/target/swap.json -o circuits/target/vk
// Re-generate after any circuit change, then redeploy.
//
// IMPORTANT: This constant is intentionally left as a 0-byte placeholder.
// Replace it with the actual VK bytes produced by the build pipeline:
//   1. Run `./circuits/scripts/build.sh` (after `nargo compile`)
//   2. Copy `circuits/target/vk` to `contracts/ultrahonk-verifier/vk`
//   3. Uncomment the include_bytes! line and remove the &[] placeholder
//
const VK_BYTES: &[u8] = include_bytes!("../vk");

// ── Error types ──────────────────────────────────────────────────────────────

/// Contract-level errors returned by verify().
#[contracterror]
#[repr(u32)]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum Error {
    /// VK bytes are missing or have not been embedded (build pipeline incomplete).
    VkNotEmbedded = 1,
    /// VK byte slice could not be loaded (invalid length or parameters).
    VkLoadFailed = 2,
    /// Proof byte slice does not match the expected exact length (must be PROOF_BYTES).
    ProofInvalidLength = 3,
    /// UltraHonk verification failed (invalid proof or mismatched public inputs).
    VerificationFailed = 4,
}

// ── Contract ─────────────────────────────────────────────────────────────────

/// On-chain UltraHonk proof verifier for the ZendSwap swap circuit.
///
/// The Verification Key (VK) is embedded at compile time via `include_bytes!`
/// and is therefore immutable — no admin key, no upgrade path, no governance.
///
/// Trust model: callers MUST independently verify that the embedded VK matches
/// the known-good swap circuit before trusting proof results from this contract.
///
/// Public inputs layout (5 × 32-byte big-endian field elements):
///   [0] exchange_rate     – fixed-point numerator
///   [1] rate_denominator  – fixed-point denominator
///   [2] nullifier_hash    – Poseidon2(commitment, secret)
///   [3] asset_out_public  – 0 = USDC, 1 = EURC
///   [4] merkle_root       – on-chain Merkle root
#[contract]
pub struct UltraHonkVerifierContract;

#[contractimpl]
impl UltraHonkVerifierContract {
    /// Verify an UltraHonk proof for the ZendSwap swap circuit.
    ///
    /// # Arguments
    /// * `proof`         – raw proof bytes (must be exactly PROOF_BYTES = 14592 bytes)
    /// * `public_inputs` – 5 public inputs, each as a 32-byte big-endian field element:
    ///                     [exchange_rate, rate_denominator, nullifier_hash,
    ///                      asset_out_public, merkle_root]
    ///
    /// # Returns
    /// `Ok(true)` on valid proof, `Err(Error::*)` on any failure.
    pub fn verify(
        env: Env,
        proof: Bytes,
        public_inputs: Vec<BytesN<32>>,
    ) -> Result<bool, Error> {
        // ── 1. Guard: VK must be embedded ──────────────────────────────────
        if VK_BYTES.is_empty() {
            return Err(Error::VkNotEmbedded);
        }

        // ── 2. Check proof length ──────────────────────────────────────────
        if proof.len() as usize != PROOF_BYTES {
            return Err(Error::ProofInvalidLength);
        }

        // ── 3. Concatenate public inputs into a flat byte blob ─────────────
        // The verifier library expects all public inputs as a single Bytes
        // blob: 5 × 32 bytes = 160 bytes total, in declaration order.
        let mut pi_bytes = Bytes::new(&env);
        for pi in public_inputs.iter() {
            pi_bytes.append(&Bytes::from_array(&env, &pi.to_array()));
        }

        // ── 4. Load VK and verify ──────────────────────────────────────────
        let vk_bytes_sdk = Bytes::from_slice(&env, VK_BYTES);
        let verifier = UltraHonkVerifier::new(&env, &vk_bytes_sdk)
            .map_err(|_| Error::VkLoadFailed)?;

        verifier
            .verify(&env, &proof, &pi_bytes)
            .map(|_| true)
            .map_err(|_| Error::VerificationFailed)
    }

    /// Returns the embedded VK as raw bytes, so callers can independently
    /// verify the circuit commitment without trusting the deployer.
    pub fn vk_bytes(env: Env) -> Bytes {
        Bytes::from_slice(&env, VK_BYTES)
    }

    /// Returns the expected proof length in bytes (PROOF_BYTES constant from
    /// the ultrahonk_soroban_verifier library).
    pub fn proof_bytes_len(_env: Env) -> u32 {
        PROOF_BYTES as u32
    }
}

#[cfg(test)]
mod test {
    use super::*;
    use soroban_sdk::Env;

    #[test]
    fn test_empty_vk_returns_error() {
        // With VK_BYTES = &[], verify() should return VkNotEmbedded.
        let env = Env::default();
        let contract_id = env.register(UltraHonkVerifierContract, ());
        let client = UltraHonkVerifierContractClient::new(&env, &contract_id);

        let dummy_proof = Bytes::from_array(&env, &[0u8; 32]);
        let empty_inputs: Vec<BytesN<32>> = Vec::new(&env);

        let result = client.try_verify(&dummy_proof, &empty_inputs);
        assert!(result.is_err());
    }
}
