import { poseidon2Hash } from '@zkpassport/poseidon2';
import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';

const TREE_DEPTH = 20;
const SECRET = BigInt(
  '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef'
);

function toHex(n: bigint): string {
  return '0x' + n.toString(16).padStart(64, '0');
}

function toField(n: bigint): string {
  return n.toString(10);
}

function runCommandInWsl(cmd: string): string {
  try {
    return execSync(`export PATH="$HOME/.nargo/bin:$HOME/.bb:$PATH" && ${cmd}`, { encoding: 'utf-8' });
  } catch (error: any) {
    throw new Error(error.stdout || error.stderr || error.message);
  }
}

function toRustByteArray(bytes: Buffer): string {
  const hexes = Array.from(bytes).map(b => '0x' + b.toString(16).padStart(2, '0'));
  let result = '&[\n';
  for (let i = 0; i < hexes.length; i += 12) {
    result += '    ' + hexes.slice(i, i + 12).join(', ') + ',\n';
  }
  result += ']';
  return result;
}

function toRustBytes32Array(n: bigint): string {
  const hex = n.toString(16).padStart(64, '0');
  const bytes: string[] = [];
  for (let i = 0; i < 64; i += 2) {
    bytes.push('0x' + hex.substring(i, i + 2));
  }
  return '[\n    ' + bytes.slice(0, 12).join(', ') + ',\n    ' + bytes.slice(12, 24).join(', ') + ',\n    ' + bytes.slice(24).join(', ') + '\n]';
}

interface SwapConfig {
  name: string;
  assetIn: bigint;
  assetOut: bigint;
  depositAmount: bigint;
  withdrawalAmount: bigint;
  exchangeRate: bigint;
  rateDenominator: bigint;
}

async function main() {
  const configs: SwapConfig[] = [
    {
      name: 'USDC_TO_EURC',
      assetIn: 0n, // USDC
      assetOut: 1n, // EURC
      depositAmount: 500n,
      withdrawalAmount: 460n,
      exchangeRate: 9200000n,
      rateDenominator: 10000000n
    },
    {
      name: 'EURC_TO_USDC',
      assetIn: 1n, // EURC
      assetOut: 0n, // USDC
      depositAmount: 500n,
      withdrawalAmount: 460n,
      exchangeRate: 9200000n,
      rateDenominator: 10000000n
    }
  ];

  let rustFixtures = `// =============================================================================
// Auto-generated by circuits/scripts/generate-test-fixtures.ts.
// Do NOT modify this file manually.
// =============================================================================

`;

  // Compute Merkle tree zeros
  const zeros: bigint[] = new Array(TREE_DEPTH);
  zeros[0] = poseidon2Hash([0n]);
  for (let i = 1; i < TREE_DEPTH; i++) {
    zeros[i] = poseidon2Hash([zeros[i - 1], zeros[i - 1]]);
  }
  const pathElements: bigint[] = zeros.slice(0, TREE_DEPTH);
  const pathIndices: number[] = new Array(TREE_DEPTH).fill(0);

  for (const config of configs) {
    console.log(`Generating proof for ${config.name}...`);

    const commitment = poseidon2Hash([config.depositAmount, config.assetIn, SECRET]);
    const nullifierHash = poseidon2Hash([commitment, SECRET]);

    let current = commitment;
    for (let i = 0; i < TREE_DEPTH; i++) {
      current = poseidon2Hash([current, zeros[i]]);
    }
    const merkleRoot = current;

    // Format Prover.toml content
    const lines: string[] = [
      `deposit_amount    = "${toField(config.depositAmount)}"`,
      `withdrawal_amount = "${toField(config.withdrawalAmount)}"`,
      `secret            = "${toHex(SECRET)}"`,
      `asset_in          = "${toField(config.assetIn)}"`,
      `asset_out         = "${toField(config.assetOut)}"`,
      `path_elements = [${pathElements.map(e => `"` + toHex(e) + `"`).join(', ')}]`,
      `path_indices = [${pathIndices.map(i => `"` + toField(BigInt(i)) + `"`).join(', ')}]`,
      `exchange_rate    = "${toField(config.exchangeRate)}"`,
      `rate_denominator = "${toField(config.rateDenominator)}"`,
      `nullifier_hash   = "${toHex(nullifierHash)}"`,
      `asset_out_public = "${toField(config.assetOut)}"`,
      `merkle_root      = "${toHex(merkleRoot)}"`
    ];

    const projectRoot = path.resolve(__dirname, '..');
    const proverTomlPath = path.join(projectRoot, 'Prover.toml');
    fs.writeFileSync(proverTomlPath, lines.join('\n'), 'utf-8');

    // Run Nargo execution & Prover
    runCommandInWsl('nargo compile');
    runCommandInWsl('nargo execute');
    runCommandInWsl('bb prove --scheme ultra_honk --oracle_hash keccak --bytecode_path target/swap.json --witness_path target/swap.gz --output_path target/proof --output_format bytes_and_fields');

    // Read proof
    const proofPath = path.join(projectRoot, 'target', 'proof', 'proof');
    const proofBytes = fs.readFileSync(proofPath);

    // Build Rust fixture variables
    rustFixtures += `// --- ${config.name} Swap Fixtures ---\n`;
    rustFixtures += `pub const ${config.name}_COMMITMENT: [u8; 32] = ${toRustBytes32Array(commitment)};\n\n`;
    rustFixtures += `pub const ${config.name}_NULLIFIER: [u8; 32] = ${toRustBytes32Array(nullifierHash)};\n\n`;
    rustFixtures += `pub const ${config.name}_ROOT: [u8; 32] = ${toRustBytes32Array(merkleRoot)};\n\n`;
    rustFixtures += `pub const ${config.name}_PROOF: &[u8] = ${toRustByteArray(proofBytes)};\n\n`;
  }

  const contractsDir = path.resolve(__dirname, '..', '..', 'contracts', 'zendswap-pool', 'src');
  const fixturesOutputPath = path.join(contractsDir, 'test_fixtures.rs');
  fs.writeFileSync(fixturesOutputPath, rustFixtures, 'utf-8');
  console.log(`✅ Success! Fixtures exported to contracts/zendswap-pool/src/test_fixtures.rs`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
